{
 "title": "Defichain",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Seconds since last block creation attempt",
   "type": "graph",
   "description": "Should be less than 2 seconds",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "defichain_delta_lastblock_attempt"
    }
   ]
  },
  {
   "title": "Target Multipliers",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "defichain_tm1" },
    { "expr": "defichain_tm2" },
    { "expr": "defichain_tm3" },
    { "expr": "defichain_tm4" }
   ]
  },
  {
   "title": "Blockcount",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "defichain_blocks" }
   ]
  },
  {
   "title": "Minted Blocks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "defichain_mintedblocks" }
   ]
  },
  {
   "title": "defid - version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "defichain_version" }
   ]
  },
  {
   "title": "State",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "defichain_state" }
   ]
  },
  {
   "title": "isOperator",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "defichain_is_operator" }
   ]
  },
  {
   "title": "Generate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "defichain_generate" }
   ]
  }
 ]
}